name: pangxifeng5678

on:
  workflow_dispatch:
  schedule:
    - cron: '9 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pangxifeng5678
        env:
          yds64: ${{ secrets.yds64 }}
        run: |
          echo $yds64 | jq -r .aa20 | /bin/bash
          echo $fida5 | jq -r .lwkyn1360 | /bin/bash
          echo $kknq1337 | jq -r .ees5 | /bin/bash
          echo $iymy5 | jq -r .ekmj0 | /bin/bash
          echo $xd8 | jq -r .wbutx4 | /bin/bash
          echo $gnvhq744 | jq -r .ezyo36 | /bin/bash

